require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0' 
#platform :ios, '10.0'
target 'Nuzzle' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

 # React Native Maps dependencies
 rn_maps_path = '../node_modules/react-native-maps'
 pod 'react-native-google-maps', :path => rn_maps_path
 pod 'GoogleMaps'
 pod 'Google-Maps-iOS-Utils'
  
  
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  
  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'RNAppleAuthentication', :path => '../node_modules/@invertase/react-native-apple-authentication'

  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'

  pod 'react-native-geocoder', :path => '../node_modules/react-native-geocoder'

  pod 'react-native-slider', :path => '../node_modules/@react-native-community/slider'

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-community/google-signin'

  pod 'RNFBStorage', :path => '../node_modules/@react-native-firebase/storage'




  pod 'RNAudioRecorderPlayer', :path => '../node_modules/react-native-audio-recorder-player'

  pod 'RNSearchBar', :path => '../node_modules/react-native-search-bar'

  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  pod 'RNCCheckbox', :path => '../node_modules/@react-native-community/checkbox'

  #pod 'jesster2k10-react-native-range-slider', :path => '../node_modules/@jesster2k10/react-native-range-slider'

  
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  # pod 'FBSDKCoreKit'
  # pod 'FBSDKLoginKit'
  # pod 'FBSDKShareKit'
  

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'react-native-pager-view', :path => '../node_modules/react-native-pager-view'

  target 'NuzzleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
   # flipper_post_install(installer)
 # end
end

target 'Nuzzle-tvOS' do
  # Pods for Nuzzle-tvOS

  target 'Nuzzle-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
