export default {
  SPLASH: {
    SPLASHLOGO: require('../assests/Splash/biglogo.png'),
   SPLASHBACKGROUND: require('../assests/Splash/Path1.png'),
   NUZZELWHITETEXT: require('../assests/Splash/NuzzelText.png'),
    NUZZELGRAYEXT: require('../assests/Splash/nuzzelGText.png'),
    BACKIMG: require('../assests/Splash/leftback.png'),
    BACKBLACK: require('../assests/Splash/backBlack.png'),
    SEARCH: require('../assests/Splash/search.png'),
    HEART: require('../assests/Splash/heart.png'),
    CROSS: require('../assests/Splash/cross.png'),
    BACKIMGCROSS: require('../assests/Splash/cross1.png'),
    LOCATIONWHITE: require('../assests/Splash/locationWhite.png'),
    LOCATIONGRAY: require('../assests/Splash/locationGray.png'),
    MARKERWHITE: require('../assests/Splash/markerWhite.png'),
    MARKERGRAY: require('../assests/Splash/markerGray.png'),
    CROSS: require('../assests/Splash/cross.png'),
    FLASH: require('../assests/Splash/flash.png'),
    PATHBACKGROUND: require('../assests/Splash/PathBackGround.png'),
    FB: require('../assests/Splash/fb.png'),
    GOOGLE: require('../assests/Splash/gogl.png'),
    APPLE: require('../assests/Splash/apple.png'),
  },
  HOME: {
    HOMEICON: require('../assests/Tabs/Home.png'),
    NUZZELUP: require('../assests/Tabs/NuzzelUp.png'),
    HOME: require('../assests/Tabs/HomeIcon.png'),
    COMPASS: require('../assests/Tabs/Compass.png'),
    CHAT: require('../assests/Tabs/Chat.png'),
    FLASH: require('../assests/Tabs/FlashIcon.png'),
  },
  NUZZLEUP: {
    FILTER: require('../assests/NuzzleUp/filter.png'),
    SETTING: require('../assests/NuzzleUp/setting.png'),
    USER: require('../assests/NuzzleUp/dummyUser.png'),
    CROSS: require('../assests/NuzzleUp/cross.png'),
    LOGOUT: require('../assests/NuzzleUp/logout.png'),
    UPLAOD: require('../assests/NuzzleUp/uploadImage.png'),
    SEND_BUTTON: require('../assests/NuzzleUp/send.png'),
    RECORD: require('../assests/NuzzleUp/record.png'),
    PLAY_RECORD: require('../assests/NuzzleUp/playrecord.png'),
    PAUSE_RECORD: require('../assests/NuzzleUp/pauserecord.png'),
    STOP_RECORD: require('../assests/NuzzleUp/stoprecord.png'),
    SMILE: require('../assests/NuzzleUp/smile.png'),
  },
  PROFILE: {
    FILTER: require('../assests/Profile/Heart.png'),
    USERPROFILE: require('../assests/Profile/userProfile1.png'),
    ADD: require('../assests/Profile/add.png'),
    HEADTOTOE: require('../assests/Profile/headtotoe.png'),
    BOOST: require('../assests/Profile/boostNew.png'),
  },
};
